variables:
  DOCKER_REPOSITORY: mendersoftware/integration-test-runner

stages:
  - test
  - build
  - publish
  - sync

include:
  - project: 'Northern.tech/Mender/mendertesting'
    file: '.gitlab-ci-check-golang-static.yml'
  - project: 'Northern.tech/Mender/mendertesting'
    file: '.gitlab-ci-check-golang-unittests.yml'
  - project: 'Northern.tech/Mender/mendertesting'
    file: '.gitlab-ci-check-docker-build.yml'
  - project: 'Northern.tech/Mender/mendertesting'
    file: '.gitlab-ci-github-status-updates.yml'
  - project: 'Northern.tech/Mender/mendertesting'
    file: '.gitlab-ci-check-docker-deploy.yml'

test:acceptance_tests:
  stage: test
  tags:
    - docker
  image: tiangolo/docker-with-compose
  services:
    - docker:19.03.5-dind
  script:
    - make acceptance-testing-build
    - make acceptance-testing-up
    - sh -c "sleep 30"
    - make acceptance-testing-run
  after_script:
    - make acceptance-testing-logs
    - make acceptance-testing-down

sync:image:
  variables:
    TARGET_MANIFEST_FILE: "kubernetes/mender-test-runner/test-runner-deployment.yaml"
